###### Imports and Settings

In [3]:
import pandas as pd
import numpy as np
import requests
#import io
import pickle
from collections import deque
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
pd.set_option('display.width', 150)
pd.options.mode.chained_assignment = None  # default='warn'

In [4]:
def percent(x, y):
    return (x/y)*100

## Calculations

## ALL:

## Total Population  
## Age Sex Race Summary:  
### Age Brackets
+ M and F U5, 5 to 9, 10 to 14, 15 to 17, 18 to 24, 25 to 34, 35 to 44, 45 to 54, 55 to 64, 65 to 74, 75 to 84, 85+  
+ for population pyramid normalizing add: 5 to 14, 15 to 24
+ age brackets: under 18, 18 to 54, 55+  
+ 65+  
### Race/Ethnicity #s   
+ White Alone  
+ Black/African American Alone  
+ American Indian Alaska Native Alone  
+ Asian Alone  
+ Native Hawaiian/Other Pacific Islander Alone  
+ Some Other Race Alone  
+ Two or More Races  
+ Hispanic/Latino  
+ White, Not Hispanic/Latino  
+ Total Minority (non-white, non Hispanic/Latino)  
## Household Summary
### Households by Household Type  
+ Total Households  
+ Family Households  
+ Family Households: Married-Couple Family  
+ Family Households: Other Family  
+ Family Households: Other Family: Male Householder no Wife Present  
+ Family Households: Other Family: Female Householder no Husband Present  
+ Nonfamily Households  
+ Nonfamily Household: Male Householder  
+ Nonfamily Household: Female Householder  
*They don't have the nonfamily male or female - replaced by Householder alone or not alone*  
### Average Household Size 
Median - drop for incorporated and unincorporated  
### Occupancy Status, and Percentages  
+ Occupancy Total Households
+ Occupied  
+ Vacant  
### Tenure, and Percentages  
+ Tenure Total Households  
+ Owners  
+ Renters

In [10]:
data = pd.read_csv('../../../../Parent-Data-Gathering/data guides/DATA GUIDE SF12000.csv')

In [4]:
#population
data['Population'] = data['agebysex_total_series']
data = data.drop(columns = ['agebysex_total_series','pop'])
#age sex race
#small groups m and f
data['Male Under 5'] = data['age_m_u5']
data['Female Under 5'] = data['age_f_u5']
data['Male 5 to 14'] = data['age_m_5to9'] + data['age_m_10to14']
data['Female 5 to 14'] = data['age_f_5to9'] + data['age_f_10to14']
data['Male 15 to 24'] = data['age_m_15to17'] + data['age_m_18to19']+data['age_m_20']+data['age_m_21']+data['age_m_22to24']
data['Female 15 to 24'] = data['age_f_15to17'] + data['age_f_18to19']+data['age_f_20']+data['age_f_21']+data['age_f_22to24']
data['Male 5 to 9'] = data['age_m_5to9']
data['Female 5 to 9'] = data['age_f_5to9']
data['Male 10 to 14'] = data['age_m_10to14']
data['Female 10 to 14'] = data['age_f_10to14']
data['Male 15 to 17'] = data['age_m_15to17']
data['Female 15 to 17'] = data['age_f_15to17']
data['Male 18 to 24'] = data['age_m_18to19']+data['age_m_20']+data['age_m_21']+data['age_m_22to24']
data['Female 18 to 24'] = data['age_f_18to19']+data['age_f_20']+data['age_f_21']+data['age_f_22to24']
data['Male 25 to 34'] = data['age_m_25to29']+data['age_m_30to34']
data['Female 25 to 34'] = data['age_f_25to29']+data['age_f_30to34']
data['Male 35 to 44'] = data['age_m_35to39']+data['age_m_40to44']
data['Female 35 to 44'] = data['age_f_35to39']+data['age_f_40to44']
data['Male 45 to 54'] = data['age_m_45to49']+data['age_m_50to54']
data['Female 45 to 54'] = data['age_f_45to49']+data['age_f_50to54']
data['Male 55 to 64'] = data['age_m_55to59']+data['age_m_60to61']+data['age_m_62to64']
data['Female 55 to 64'] = data['age_f_55to59']+data['age_f_60to61']+data['age_f_62to64']
data['Male 65 to 74'] = data['age_m_65to66']+data['age_m_67to69']+data['age_m_70to74']
data['Female 65 to 74'] = data['age_f_65to66']+data['age_f_67to69']+data['age_f_70to74']
data['Male 75 to 84'] = data['age_m_75to79']+data['age_m_80to84']
data['Female 75 to 84'] = data['age_f_75to79']+data['age_f_80to84']
data['Male 85 and Older'] = data['age_m_85+']
data['Female 85 and Older'] = data['age_f_85+']
#age group breakouts
data['Age:Under 5'] = data['Male Under 5']+data['Female Under 5']
data['Age %:Under 5'] = percent(data['Age:Under 5'], data['Population'])
data['Age:5 to 9'] = data['Male 5 to 9']+data['Female 5 to 9']
data['Age%:5 to 9'] = percent(data['Age:5 to 9'], data['Population'])
data['Age:10 to 14'] = data['Male 10 to 14']+data['Female 10 to 14']
data['Age%:10 to 14'] = percent(data['Age:10 to 14'], data['Population'])
data['Age:15 to 17'] = data['Male 15 to 17']+data['Female 15 to 17']
data['Age%:15 to 17'] = percent(data['Age:15 to 17'], data['Population'])
data['Age:18 to 24'] = data['Male 18 to 24']+data['Female 18 to 24']
data['Age%:18 to 24'] = percent(data['Age:18 to 24'], data['Population'])
data['Age:25 to 34'] = data['Male 25 to 34']+data['Female 25 to 34']
data['Age%:25 to 34'] = percent(data['Age:25 to 34'], data['Population'])
data['Age:35 to 44'] = data['Male 35 to 44']+data['Female 35 to 44']
data['Age%:35 to 44'] = percent(data['Age:35 to 44'], data['Population'])
data['Age:45 to 54'] = data['Male 35 to 44']+data['Female 45 to 54']
data['Age%:45 to 54'] = percent(data['Age:45 to 54'], data['Population'])
data['Age:55 to 64'] = data['Male 55 to 64']+data['Female 55 to 64']
data['Age%:55 to 64'] = percent(data['Age:55 to 64'], data['Population'])
data['Age:65 to 74'] = data['Male 65 to 74']+data['Female 65 to 74']
data['Age%:65 to 74'] = percent(data['Age:65 to 74'], data['Population'])
data['Age:75 to 84'] = data['Male 75 to 84']+data['Female 75 to 84']
data['Age%:75 to 84'] = percent(data['Age:75 to 84'], data['Population'])
data['Age:85 and Older'] = data['Male 85 and Older']+data['Female 85 and Older']
data['Age%:85 and Older'] = percent(data['Age:85 and Older'], data['Population'])
data['Age:School Age 5 to 18'] = data['Age:5 to 9']+data['Age:10 to 14']+data['Age:15 to 17']
data['Age%:School Age 5 to 18'] = percent(data['Age:School Age 5 to 18'], data['Population'])
#age brackets
u18list = [data['Male Under 5'],data['Female Under 5'],data['Male 5 to 9'],data['Female 5 to 9'],data['Male 10 to 14'],data['Female 10 to 14'],data['Male 15 to 17'],
           data['Female 15 to 17']]
data['Age:Under 18'] = sum(u18list)
data['Age%:Under 18'] = percent(data['Age:Under 18'], data['Population'])
eighteento54list = [data['Male 18 to 24'],data['Female 18 to 24'],data['Male 25 to 34'],data['Female 25 to 34'],data['Male 35 to 44'],data['Female 35 to 44'],
              data['Male 45 to 54'],data['Female 45 to 54']]
data['Age:18 to 54'] = sum(eighteento54list)
data['Age%:18 to 54'] = percent(data['Age:18 to 54'], data['Population'])
fifty5pluslist = [data['Male 55 to 64'],data['Female 55 to 64'],data['Male 65 to 74'],data['Female 65 to 74'],data['Male 75 to 84'],data['Female 75 to 84'],
                  data['Male 85 and Older'],data['Female 85 and Older']]
data['Age:55 and Older'] = sum(fifty5pluslist)
data['Age%:55 and Older'] = percent(data['Age:55 and Older'], data['Population'])

#65+
sixty5pluslist = [data['Male 65 to 74'],data['Female 65 to 74'],data['Male 75 to 84'],data['Female 75 to 84'],data['Male 85 and Older'],data['Female 85 and Older']]
data['Age:65 and Older'] = sum(sixty5pluslist)
data['Age%:65 and Older'] = percent(data['Age:65 and Older'], data['Population'])

cols = ['age_total_male','age_total_female','age_m_u5','age_m_5to9','age_m_10to14','age_m_15to17','age_m_18to19','age_m_20','age_m_21','age_m_22to24','age_m_25to29','age_m_30to34','age_m_35to39',
        'age_m_40to44','age_m_45to49','age_m_50to54','age_m_55to59','age_m_60to61','age_m_62to64','age_m_65to66','age_m_67to69','age_m_70to74','age_m_75to79',
        'age_m_80to84','age_m_85+','age_f_u5','age_f_5to9','age_f_10to14','age_f_15to17','age_f_18to19','age_f_20','age_f_21','age_f_22to24','age_f_25to29',
        'age_f_30to34','age_f_35to39','age_f_40to44','age_f_45to49','age_f_50to54','age_f_55to59','age_f_60to61','age_f_62to64','age_f_65to66','age_f_67to69',
        'age_f_70to74','age_f_75to79','age_f_80to84','age_f_85+']
data = data.drop(columns = cols)

#race and ethnicity
#White Alone
data['White Alone'] = data['raceeth_white_alone']
data['White Alone %'] = percent(data['White Alone'], data['Population'])
#Population not White
data['Non-White Population: Race'] = data['Population'] - data['White Alone']
#Black or African American Alone 
data['Black or African American Alone'] = data['raceeth_blackafricanamerican_alone']
data['Black or African American Alone %'] = percent(data['Black or African American Alone'], data['Population'])
data['Black or African American Alone % Non-White Population'] = percent(data['Black or African American Alone'], data['Non-White Population: Race'])
#American Indian and Alaska Native Alone
data['American Indian Alaska Native Alone'] = data['raceeth_americanindianalaskanative_alone']
data['American Indian Alaska Native Alone %'] = percent(data['American Indian Alaska Native Alone'], data['Population'])
data['American Indian Alaska Native Alone % Non-White Population'] = percent(data['American Indian Alaska Native Alone'], data['Non-White Population: Race'])
#Asian Alone
data['Asian Alone'] = data['raceeth_asian_alone']
data['Asian Alone %'] = percent(data['Asian Alone'], data['Population'])
data['Asian Alone % Non-White Population'] = percent(data['Asian Alone'], data['Non-White Population: Race'])
#Native Hawaiian Other Pacific Islander Alone
data['Native Hawaiian Other Pacific Islander Alone'] = data['raceeth_nativehawaiianotherpacificislander_alone']
data['Native Hawaiian Other Pacific Islander Alone %'] = percent(data['Native Hawaiian Other Pacific Islander Alone'], data['Population'])
data['Native Hawaiian Other Pacific Islander Alone % Non-White Population'] = percent(data['Native Hawaiian Other Pacific Islander Alone'], data['Non-White Population: Race'])
#Some Other Race Alone
data['Some Other Race Alone'] = data['raceeth_someotherrace_alone']
data['Some Other Race Alone %'] = percent(data['Some Other Race Alone'],data['Population'])
data['Some Other Race Alone % Non-White Population'] = percent(data['Some Other Race Alone'], data['Non-White Population: Race'])
#Two or More Races
data['Two or More Races'] = data['raceeth_twoormoreraces_alone']
data['Two or More Races %'] = percent(data['Two or More Races'], data['Population'])
data['Two or More Races % Non-White Population'] = percent(data['Two or More Races'], data['Non-White Population: Race'])
#Hispanic or Latino
data['Hispanic or Latino'] = data['raceeth_hispanicorlatino']
data['Hispanic or Latino %'] = percent(data['Hispanic or Latino'], data['Population'])
#not hispanic or latino
data['Not Hispanic or Latino'] = data['Population'] - data['Hispanic or Latino']
data['Not Hispanic or Latino %'] = percent(data['Not Hispanic or Latino'], data['Population'])
#Data Minority
data['Minority'] = data['Population'] - data['raceeth_whitealone_nothispanicorlatino']
data['Minority %'] = percent(data['Minority'], data['Population'])
#not minority
data['White Alone Not Hispanic or Latino'] = data['raceeth_whitealone_nothispanicorlatino']
data['White Alone Not Hispanic or Latino %'] = percent(data['White Alone Not Hispanic or Latino'], data['Population'])
cols = ['raceeth_total_series','raceeth_white_alone','raceeth_blackafricanamerican_alone','raceeth_americanindianalaskanative_alone','raceeth_asian_alone',
        'raceeth_nativehawaiianotherpacificislander_alone','raceeth_someotherrace_alone','raceeth_twoormoreraces_alone','raceeth_hispanicorlatino',
        'raceeth_whitealone_nothispanicorlatino','raceeth_total_oneracealone']
data = data.drop(columns = cols)

#households
data['Total Households'] = data['hhtype_total_series']
data['Family Households'] = data['hhtype_twoormore_family']
data['Family Households: Married Couple Family'] = data['hhtype_twoormore_family_marriedcouplefam']
data['Household Type%: Family, Married Couple Households'] = percent(data['Family Households: Married Couple Family'], data['hhtype_total_series'])
data['Family Households: Not Married Couple Family'] = data['hhtype_twoormore_family_otherfam']
data['Household Type%: Family, Not Married Couple Households'] = percent(data['Family Households: Not Married Couple Family'], data['hhtype_total_series'])
data['Family Households: Not Married Couple: Male no Spouse'] = data['hhtype_twoormore_family_otherfam_malenospouse']
data['Family Households: Not Married Couple: Female no Spouse'] = data['hhtype_twoormore_family_otherfam_femalenospouse']
data['Nonfamily Households'] = data['hhtype_twoormore_nonfamily'] + data['hhtype_oneperson']
data['Nonfamily Households: Householder Alone'] = data['hhtype_oneperson']
data['Household Type%: Nonfamily, Householder Alone'] = percent(data['Nonfamily Households: Householder Alone'], data['hhtype_total_series'])
data['Nonfamily Households: Householder not Alone'] = data['hhtype_twoormore_nonfamily']
data['Household Type%: Nonfamily, Householder Not Alone'] = percent(data['Nonfamily Households: Householder not Alone'], data['hhtype_total_series'])

cols = ['hhtype_total_series','hhtype_oneperson','hhtype_oneperson_male','hhtype_oneperson_female','hhtype_twoormore','hhtype_twoormore_family',
        'hhtype_twoormore_family_marriedcouplefam','hhtype_twoormore_family_marriedcouplefam_ownchildrenunder18',
        'hhtype_twoormore_family_marriedcouplefam_noownchildrenunder18','hhtype_twoormore_family_otherfam','hhtype_twoormore_family_otherfam_malenospouse',
        'hhtype_twoormore_family_otherfam_malenospouse_ownchildrenunder18','hhtype_twoormore_family_otherfam_malenospouse_noownchildrenunder18',
        'hhtype_twoormore_family_otherfam_femalenospouse','hhtype_twoormore_family_otherfam_femalenospouse_ownchildrenunder18',
        'hhtype_twoormore_family_otherfam_femalenospouse_noownchildrenunder18','hhtype_twoormore_nonfamily','hhtype_twoormore_nonfamily_male',
        'hhtype_twoormore_nonfamily_female']
data = data.drop(columns = cols)
#average household size
data['Average Household Size'] = data['hhsize_avg']
data = data.drop(columns = ['hhsize_avg'])
#occupancy
data['Occupancy:Total Households'] = data['occupancy_total_series']
data['Occupancy:Occupied Units'] = data['occupancy_occupiedunits']
data['Occupancy%:Occupied Units'] = percent(data['Occupancy:Occupied Units'], data['Occupancy:Total Households'])
data['Occupancy:Vacant Units'] = data['occupancy_vacantunits']
data['Occupancy%:Vacant Units'] = percent(data['Occupancy:Vacant Units'], data['Occupancy:Total Households'])
cols = ['occupancy_total_series','occupancy_occupiedunits','occupancy_vacantunits']
data = data.drop(columns = cols)
#tenure
data['Tenure:Total Households'] = data['tenure_total_series']
data['Tenure:Owners'] = data['tenure_owneroccunits']
data['Tenure%:Owners'] = percent(data['Tenure:Owners'], data['Tenure:Total Households'])
data['Tenure:Renters'] = data['tenure_renteroccunits']
data['Tenure%:Renters'] = percent(data['Tenure:Renters'], data['Tenure:Total Households'])
cols = ['units_allhousing','tenure_total_series','tenure_owneroccunits','tenure_renteroccunits']
data = data.drop(columns = cols)
data = data.drop(columns = ['StateFIPS', 'GeoFIPS'])
data.head()

,NAME,GEO_ID,Population,Male Under 5,Female Under 5,Male 5 to 14,Female 5 to 14,Male 15 to 24,Female 15 to 24,Male 5 to 9,Female 5 to 9,Male 10 to 14,Female 10 to 14,Male 15 to 17,Female 15 to 17,Male 18 to 24,Female 18 to 24,Male 25 to 34,Female 25 to 34,Male 35 to 44,Female 35 to 44,Male 45 to 54,Female 45 to 54,Male 55 to 64,Female 55 to 64,Male 65 to 74,Female 65 to 74,Male 75 to 84,Female 75 to 84,Male 85 and Older,Female 85 and Older,Age:Under 5,Age %:Under 5,Age:5 to 9,Age%:5 to 9,Age:10 to 14,Age%:10 to 14,Age:15 to 17,Age%:15 to 17,Age:18 to 24,Age%:18 to 24,Age:25 to 34,Age%:25 to 34,Age:35 to 44,Age%:35 to 44,Age:45 to 54,Age%:45 to 54,Age:55 to 64,Age%:55 to 64,Age:65 to 74,Age%:65 to 74,Age:75 to 84,Age%:75 to 84,Age:85 and Older,Age%:85 and Older,Age:School Age 5 to 18,Age%:School Age 5 to 18,Age:Under 18,Age%:Under 18,Age:18 to 54,Age%:18 to 54,Age:55 and Older,Age%:55 and Older,Age:65 and Older,Age%:65 and Older,White Alone,White Alone %,Non-White Population: Race,Black or African American Alone,Black or African American Alone %,Black or African American Alone % Non-White Population,American Indian Alaska Native Alone,American Indian Alaska Native Alone %,American Indian Alaska Native Alone % Non-White Population,Asian Alone,Asian Alone %,Asian Alone % Non-White Population,Native Hawaiian Other Pacific Islander Alone,Native Hawaiian Other Pacific Islander Alone %,Native Hawaiian Other Pacific Islander Alone % Non-White Population,Some Other Race Alone,Some Other Race Alone %,Some Other Race Alone % Non-White Population,Two or More Races,Two or More Races %,Two or More Races % Non-White Population,Hispanic or Latino,Hispanic or Latino %,Not Hispanic or Latino,Not Hispanic or Latino %,Minority,Minority %,White Alone Not Hispanic or Latino,White Alone Not Hispanic or Latino %,Total Households,Family Households,Family Households: Married Couple Family,"Household Type%: Family, Married Couple Households",Family Households: Not Married Couple Family,"Household Type%: Family, Not Married Couple Households",Family Households: Not Married Couple: Male no Spouse,Family Households: Not Married Couple: Female no Spouse,Nonfamily Households,Nonfamily Households: Householder Alone,"Household Type%: Nonfamily, Householder Alone",Nonfamily Households: Householder not Alone,"Household Type%: Nonfamily, Householder Not Alone",Average Household Size,Occupancy:Total Households,Occupancy:Occupied Units,Occupancy%:Occupied Units,Occupancy:Vacant Units,Occupancy%:Vacant Units,Tenure:Total Households,Tenure:Owners,Tenure%:Owners,Tenure:Renters,Tenure%:Renters
0,"Cheatham County, Tennessee",0500000US47021,35912.0,1372.0,1187.0,2960.0,2728.0,2196.0,2096.0,1473.0,1330.0,1487.0,1398.0,829.0,854.0,1367.0,1242.0,2521.0,2688.0,3404.0,3429.0,2642.0,2533.0,1559.0,1512.0,878.0,962.0,361.0,531.0,88.0,265.0,2559.0,7.125752,2803.0,7.805190,2885.0,8.033526,1683.0,4.686456,2609.0,7.264981,5209.0,14.504901,6833.0,19.027066,5937.0,16.532078,3071.0,8.551459,1840.0,5.123636,892.0,2.483849,353.0,0.982958,7371.0,20.525173,9930.0,27.650924,19826.0,55.207173,6156.0,17.141902,3085.0,8.590443,34783.0,96.856204,1129.0,532.0,1.481399,47.121346,135.0,0.375919,11.957484,63.0,0.175429,5.580159,17.0,0.047338,1.505757,130.0,0.361996,11.514615,252.0,0.701715,22.320638,437.0,1.216863,35475.0,98.783137,1406.0,3.915126,34506.0,96.084874,12878.0,10162.0,8356.0,64.885852,1806.0,14.023917,564.0,1242.0,2716.0,2177.0,16.904799,539.0,4.185433,2.76,13508.0,12878.0,95.336097,630.0,4.663903,12878.0,10773.0,83.654294,2105.0,16.345706
1,"Davidson County, Tennessee",0500000US47037,569891.0,19466.0,18347.0,35289.0,33667.0,42732.0,43144.0,18200.0,17524.0,17089.0,16143.0,10120.0,9558.0,32612.0,33586.0,51053.0,49134.0,46237.0,47262.0,36358.0,38676.0,20839.0,24243.0,13996.0,19402.0,7902.0,14142.0,1993.0,6009.0,37813.0,6.635128,35724.0,6.268567,33232.0,5.831291,19678.0,3.452941,66198.0,11.615905,100187.0,17.580028,93499.0,16.406471,84913.0,14.899867,45082.0,7.910636,33398.0,5.860419,22044.0,3.868108,8002.0,1.404128,88634.0,15.552799,126447.0,22.187927,334918.0,58.768782,108526.0,19.043291,63444.0,11.132655,381783.0,66.992284,188108.0,147696.0,25.916535,78.516597,1679.0,0.294618,0.892572,13275.0,2.329393,7.057116,403.0,0.070715,0.214239,13816.0,2.424323,7.344717,11239.0,1.972132,5.974759,26091.0,4.578244,543800.0,95.421756,198741.0,34.873511,371150.0,65.126489,237405.0,138106.0,94784.0,39.925023,43322.0,18.248141,9283.0,34039.0,99299.0,79249.0,33.381353,20050.0,8.445483,2.30,252977.0,237405.0,93.844500,15572.0,6.155500,237405.0,131340.0,55.323182,106065.0,44.676818
2,"Dickson County, Tennessee",0500000US47043,43156.0,1538.0,1437.0,3412.0,3185.0,2701.0,2706.0,1686.0,1584.0,1726.0,1601.0,957.0,957.0,1744.0,1749.0,3010.0,3108.0,3535.0,3581.0,2828.0,2944.0,2036.0,2066.0,1304.0,1520.0,656.0,1041.0,138.0,410.0,2975.0,6.893595,3270.0,7.577162,3327.0,7.709241,1914.0,4.435073,3493.0,8.093892,6118.0,14.176476,7116.0,16.489017,6479.0,15.012976,4102.0,9.505051,2824.0,6.543702,1697.0,3.932246,548.0,1.269812,8511.0,19.721476,11486.0,26.615071,22499.0,52.134118,9171.0,21.250811,5069.0,11.745760,40243.0,93.250070,2913.0,1978.0,4.583372,67.902506,172.0,0.398554,5.904566,116.0,0.268792,3.982149,5.0,0.011586,0.171644,204.0,0.472704,7.003090,438.0,1.014923,15.036045,484.0,1.121513,42672.0,98.878487,3136.0,7.266660,40020.0,92.733340,16473.0,12175.0,9604.0,58.301463,2571.0,15.607357,670.0,1901.0,4298.0,3678.0,22.327445,620.0,3.763735,2.59,17614.0,16473.0,93.522198,1141.0,6.477802,16473.0,12539.0,76.118497,3934.0,23.881503
3,"Houston County, Tennessee",0500000US47083,8088.0,268.0,273.0,577.0,541.0,481.0,422.0,311.0,243.0,266.0,298.0,174.0,137.0,307.0,285.0,520.0,484.0,555.0,548.0,546.0,567.0,467.0,489.0,343.0,384.0,189.0,264.0,53.0,117.0,541.0,6.688922,554.0,6.849654,564.0,6.973294,311.0,3.845203,592.0,7.319486,1004.0,12.413452,1103.0,13.637488,1122.0,13.872404,956.0,11.819980,727.0,8.988625,453.0,5.600890,170.0,2.101879,1429.0,17.668150,1970.0,24.357072,3812.0,47.131553,2306.0,28.511375,1350.0,16.691395,7650.0,94.584570,438.0,268.0,3.313551,61.187215,15.0,0.185460,3.424658,10.0,0.123640,2.283105,5.0,0.061820,1.141553,63.0,0.778932,14.383562,77.0,0.952028,17.579909,101.0,1.248764,7987.0,98.751236,477.0,5.897626,7611.0,94.102374,3216.0,2300.0,1833.0,56.996269,467.0,14.521144,134.0,333.0,916.0,815.0,25.342040,101.0,3.140547,2.46,3901.0,3216.0,82.440400,685.0,17.559600,3216.0,2476.0,76.990050,740.0,23.009950
4,"Humphreys County, Tennessee",0500000US47085,17929.0,567.0,505.0,1270.0,1181.0,1114.0,1011.0,610.0,597.0,660.0,584.0,402.0,357.0,712.0,654.0,1073.0,1173.0,1352.0,1337.0,1259.0,1317.0,1066.0,1049.0,705.0,823.0,339.0,526.0,74.0,188.0,1072.0,5.979140,1207.0,6.732110,1244.0,6.938480,759.0,4.233365,1366.0,7.618941,2246.0,12.527191,2689.0,14.998048,2669.0,14.886497,2115.0,11.796531,1528.0,8.522505,865.0,4.824586,262.0,1.461320,3210.0,17.903954,4282.0,23.883094,8877.0,49.511964,4770.0,26.604942,2655.0,14.808411,17125.0,95.515645,804.0,527.0,2.939372,65.547264,48.0,0.267723,5.970149,46.0,0.256568,5.721393,2.0,0.011155,0.248756,29.0,0.161749,3.606965,152.0,0.847788,18.905473,148.0,0.825478,17781.0,99.174522,899.0,5.014223,17030.0,94.985777,7238.0,5145.0,4144.0,57.253385,1001.0,13.829787,266.0,735.0,2093.0,1808.0,24.979276,285.0,3.937552,2.44,8482.0,7238.0,85.333648,1244.0,14.666352,7238.0,5641.0,77.935894,1597.0,22.064106

In [5]:
suffix = data.set_index(['NAME', 'GEO_ID'])
suffix = suffix.add_suffix(' 2000')
suffix = suffix.reset_index()
suffix.head(3)

,NAME,GEO_ID,Population 2000,Male Under 5 2000,Female Under 5 2000,Male 5 to 14 2000,Female 5 to 14 2000,Male 15 to 24 2000,Female 15 to 24 2000,Male 5 to 9 2000,Female 5 to 9 2000,Male 10 to 14 2000,Female 10 to 14 2000,Male 15 to 17 2000,Female 15 to 17 2000,Male 18 to 24 2000,Female 18 to 24 2000,Male 25 to 34 2000,Female 25 to 34 2000,Male 35 to 44 2000,Female 35 to 44 2000,Male 45 to 54 2000,Female 45 to 54 2000,Male 55 to 64 2000,Female 55 to 64 2000,Male 65 to 74 2000,Female 65 to 74 2000,Male 75 to 84 2000,Female 75 to 84 2000,Male 85 and Older 2000,Female 85 and Older 2000,Age:Under 5 2000,Age %:Under 5 2000,Age:5 to 9 2000,Age%:5 to 9 2000,Age:10 to 14 2000,Age%:10 to 14 2000,Age:15 to 17 2000,Age%:15 to 17 2000,Age:18 to 24 2000,Age%:18 to 24 2000,Age:25 to 34 2000,Age%:25 to 34 2000,Age:35 to 44 2000,Age%:35 to 44 2000,Age:45 to 54 2000,Age%:45 to 54 2000,Age:55 to 64 2000,Age%:55 to 64 2000,Age:65 to 74 2000,Age%:65 to 74 2000,Age:75 to 84 2000,Age%:75 to 84 2000,Age:85 and Older 2000,Age%:85 and Older 2000,Age:School Age 5 to 18 2000,Age%:School Age 5 to 18 2000,Age:Under 18 2000,Age%:Under 18 2000,Age:18 to 54 2000,Age%:18 to 54 2000,Age:55 and Older 2000,Age%:55 and Older 2000,Age:65 and Older 2000,Age%:65 and Older 2000,White Alone 2000,White Alone % 2000,Non-White Population: Race 2000,Black or African American Alone 2000,Black or African American Alone % 2000,Black or African American Alone % Non-White Population 2000,American Indian Alaska Native Alone 2000,American Indian Alaska Native Alone % 2000,American Indian Alaska Native Alone % Non-White Population 2000,Asian Alone 2000,Asian Alone % 2000,Asian Alone % Non-White Population 2000,Native Hawaiian Other Pacific Islander Alone 2000,Native Hawaiian Other Pacific Islander Alone % 2000,Native Hawaiian Other Pacific Islander Alone % Non-White Population 2000,Some Other Race Alone 2000,Some Other Race Alone % 2000,Some Other Race Alone % Non-White Population 2000,Two or More Races 2000,Two or More Races % 2000,Two or More Races % Non-White Population 2000,Hispanic or Latino 2000,Hispanic or Latino % 2000,Not Hispanic or Latino 2000,Not Hispanic or Latino % 2000,Minority 2000,Minority % 2000,White Alone Not Hispanic or Latino 2000,White Alone Not Hispanic or Latino % 2000,Total Households 2000,Family Households 2000,Family Households: Married Couple Family 2000,"Household Type%: Family, Married Couple Households 2000",Family Households: Not Married Couple Family 2000,"Household Type%: Family, Not Married Couple Households 2000",Family Households: Not Married Couple: Male no Spouse 2000,Family Households: Not Married Couple: Female no Spouse 2000,Nonfamily Households 2000,Nonfamily Households: Householder Alone 2000,"Household Type%: Nonfamily, Householder Alone 2000",Nonfamily Households: Householder not Alone 2000,"Household Type%: Nonfamily, Householder Not Alone 2000",Average Household Size 2000,Occupancy:Total Households 2000,Occupancy:Occupied Units 2000,Occupancy%:Occupied Units 2000,Occupancy:Vacant Units 2000,Occupancy%:Vacant Units 2000,Tenure:Total Households 2000,Tenure:Owners 2000,Tenure%:Owners 2000,Tenure:Renters 2000,Tenure%:Renters 2000
0,"Cheatham County, Tennessee",0500000US47021,35912.0,1372.0,1187.0,2960.0,2728.0,2196.0,2096.0,1473.0,1330.0,1487.0,1398.0,829.0,854.0,1367.0,1242.0,2521.0,2688.0,3404.0,3429.0,2642.0,2533.0,1559.0,1512.0,878.0,962.0,361.0,531.0,88.0,265.0,2559.0,7.125752,2803.0,7.805190,2885.0,8.033526,1683.0,4.686456,2609.0,7.264981,5209.0,14.504901,6833.0,19.027066,5937.0,16.532078,3071.0,8.551459,1840.0,5.123636,892.0,2.483849,353.0,0.982958,7371.0,20.525173,9930.0,27.650924,19826.0,55.207173,6156.0,17.141902,3085.0,8.590443,34783.0,96.856204,1129.0,532.0,1.481399,47.121346,135.0,0.375919,11.957484,63.0,0.175429,5.580159,17.0,0.047338,1.505757,130.0,0.361996,11.514615,252.0,0.701715,22.320638,437.0,1.216863,35475.0,98.783137,1406.0,3.915126,34506.0,96.084874,12878.0,10162.0,8356.0,64.885852,1806.0,14.023917,564.0,1242.0,2716.0,2177.0,16.904799,539.0,4.185433,2.76,13508.0,12878.0,95.336097,630.0,4.663903,12878.0,10773.0,83.654294,2105.0,16.345706
1,"Davidson County, Tennessee",0500000US47037,569891.0,19466.0,18347.0,35289.0,33667.0,42732.0,43144.0,18200.0,17524.0,17089.0,16143.0,10120.0,9558.0,32612.0,33586.0,51053.0,49134.0,46237.0,47262.0,36358.0,38676.0,20839.0,24243.0,13996.0,19402.0,7902.0,14142.0,1993.0,6009.0,37813.0,6.635128,35724.0,6.268567,33232.0,5.831291,19678.0,3.452941,66198.0,11.615905,100187.0,17.580028,93499.0,16.406471,84913.0,14.899867,45082.0,7.910636,33398.0,5.860419,22044.0,3.868108,8002.0,1.404128,88634.0,15.552799,126447.0,22.187927,334918.0,58.768782,108526.0,19.043291,63444.0,11.132655,381783.0,66.992284,188108.0,147696.0,25.916535,78.516597,1679.0,0.294618,0.892572,13275.0,2.329393,7.057116,403.0,0.070715,0.214239,13816.0,2.424323,7.344717,11239.0,1.972132,5.974759,26091.0,4.578244,543800.0,95.421756,198741.0,34.873511,371150.0,65.126489,237405.0,138106.0,94784.0,39.925023,43322.0,18.248141,9283.0,34039.0,99299.0,79249.0,33.381353,20050.0,8.445483,2.30,252977.0,237405.0,93.844500,15572.0,6.155500,237405.0,131340.0,55.323182,106065.0,44.676818
2,"Dickson County, Tennessee",0500000US47043,43156.0,1538.0,1437.0,3412.0,3185.0,2701.0,2706.0,1686.0,1584.0,1726.0,1601.0,957.0,957.0,1744.0,1749.0,3010.0,3108.0,3535.0,3581.0,2828.0,2944.0,2036.0,2066.0,1304.0,1520.0,656.0,1041.0,138.0,410.0,2975.0,6.893595,3270.0,7.577162,3327.0,7.709241,1914.0,4.435073,3493.0,8.093892,6118.0,14.176476,7116.0,16.489017,6479.0,15.012976,4102.0,9.505051,2824.0,6.543702,1697.0,3.932246,548.0,1.269812,8511.0,19.721476,11486.0,26.615071,22499.0,52.134118,9171.0,21.250811,5069.0,11.745760,40243.0,93.250070,2913.0,1978.0,4.583372,67.902506,172.0,0.398554,5.904566,116.0,0.268792,3.982149,5.0,0.011586,0.171644,204.0,0.472704,7.003090,438.0,1.014923,15.036045,484.0,1.121513,42672.0,98.878487,3136.0,7.266660,40020.0,92.733340,16473.0,12175.0,9604.0,58.301463,2571.0,15.607357,670.0,1901.0,4298.0,3678.0,22.327445,620.0,3.763735,2.59,17614.0,16473.0,93.522198,1141.0,6.477802,16473.0,12539.0,76.118497,3934.0,23.881503

In [6]:
tidy = data
tidy.head(3)

,NAME,GEO_ID,Population,Male Under 5,Female Under 5,Male 5 to 14,Female 5 to 14,Male 15 to 24,Female 15 to 24,Male 5 to 9,Female 5 to 9,Male 10 to 14,Female 10 to 14,Male 15 to 17,Female 15 to 17,Male 18 to 24,Female 18 to 24,Male 25 to 34,Female 25 to 34,Male 35 to 44,Female 35 to 44,Male 45 to 54,Female 45 to 54,Male 55 to 64,Female 55 to 64,Male 65 to 74,Female 65 to 74,Male 75 to 84,Female 75 to 84,Male 85 and Older,Female 85 and Older,Age:Under 5,Age %:Under 5,Age:5 to 9,Age%:5 to 9,Age:10 to 14,Age%:10 to 14,Age:15 to 17,Age%:15 to 17,Age:18 to 24,Age%:18 to 24,Age:25 to 34,Age%:25 to 34,Age:35 to 44,Age%:35 to 44,Age:45 to 54,Age%:45 to 54,Age:55 to 64,Age%:55 to 64,Age:65 to 74,Age%:65 to 74,Age:75 to 84,Age%:75 to 84,Age:85 and Older,Age%:85 and Older,Age:School Age 5 to 18,Age%:School Age 5 to 18,Age:Under 18,Age%:Under 18,Age:18 to 54,Age%:18 to 54,Age:55 and Older,Age%:55 and Older,Age:65 and Older,Age%:65 and Older,White Alone,White Alone %,Non-White Population: Race,Black or African American Alone,Black or African American Alone %,Black or African American Alone % Non-White Population,American Indian Alaska Native Alone,American Indian Alaska Native Alone %,American Indian Alaska Native Alone % Non-White Population,Asian Alone,Asian Alone %,Asian Alone % Non-White Population,Native Hawaiian Other Pacific Islander Alone,Native Hawaiian Other Pacific Islander Alone %,Native Hawaiian Other Pacific Islander Alone % Non-White Population,Some Other Race Alone,Some Other Race Alone %,Some Other Race Alone % Non-White Population,Two or More Races,Two or More Races %,Two or More Races % Non-White Population,Hispanic or Latino,Hispanic or Latino %,Not Hispanic or Latino,Not Hispanic or Latino %,Minority,Minority %,White Alone Not Hispanic or Latino,White Alone Not Hispanic or Latino %,Total Households,Family Households,Family Households: Married Couple Family,"Household Type%: Family, Married Couple Households",Family Households: Not Married Couple Family,"Household Type%: Family, Not Married Couple Households",Family Households: Not Married Couple: Male no Spouse,Family Households: Not Married Couple: Female no Spouse,Nonfamily Households,Nonfamily Households: Householder Alone,"Household Type%: Nonfamily, Householder Alone",Nonfamily Households: Householder not Alone,"Household Type%: Nonfamily, Householder Not Alone",Average Household Size,Occupancy:Total Households,Occupancy:Occupied Units,Occupancy%:Occupied Units,Occupancy:Vacant Units,Occupancy%:Vacant Units,Tenure:Total Households,Tenure:Owners,Tenure%:Owners,Tenure:Renters,Tenure%:Renters
0,"Cheatham County, Tennessee",0500000US47021,35912.0,1372.0,1187.0,2960.0,2728.0,2196.0,2096.0,1473.0,1330.0,1487.0,1398.0,829.0,854.0,1367.0,1242.0,2521.0,2688.0,3404.0,3429.0,2642.0,2533.0,1559.0,1512.0,878.0,962.0,361.0,531.0,88.0,265.0,2559.0,7.125752,2803.0,7.805190,2885.0,8.033526,1683.0,4.686456,2609.0,7.264981,5209.0,14.504901,6833.0,19.027066,5937.0,16.532078,3071.0,8.551459,1840.0,5.123636,892.0,2.483849,353.0,0.982958,7371.0,20.525173,9930.0,27.650924,19826.0,55.207173,6156.0,17.141902,3085.0,8.590443,34783.0,96.856204,1129.0,532.0,1.481399,47.121346,135.0,0.375919,11.957484,63.0,0.175429,5.580159,17.0,0.047338,1.505757,130.0,0.361996,11.514615,252.0,0.701715,22.320638,437.0,1.216863,35475.0,98.783137,1406.0,3.915126,34506.0,96.084874,12878.0,10162.0,8356.0,64.885852,1806.0,14.023917,564.0,1242.0,2716.0,2177.0,16.904799,539.0,4.185433,2.76,13508.0,12878.0,95.336097,630.0,4.663903,12878.0,10773.0,83.654294,2105.0,16.345706
1,"Davidson County, Tennessee",0500000US47037,569891.0,19466.0,18347.0,35289.0,33667.0,42732.0,43144.0,18200.0,17524.0,17089.0,16143.0,10120.0,9558.0,32612.0,33586.0,51053.0,49134.0,46237.0,47262.0,36358.0,38676.0,20839.0,24243.0,13996.0,19402.0,7902.0,14142.0,1993.0,6009.0,37813.0,6.635128,35724.0,6.268567,33232.0,5.831291,19678.0,3.452941,66198.0,11.615905,100187.0,17.580028,93499.0,16.406471,84913.0,14.899867,45082.0,7.910636,33398.0,5.860419,22044.0,3.868108,8002.0,1.404128,88634.0,15.552799,126447.0,22.187927,334918.0,58.768782,108526.0,19.043291,63444.0,11.132655,381783.0,66.992284,188108.0,147696.0,25.916535,78.516597,1679.0,0.294618,0.892572,13275.0,2.329393,7.057116,403.0,0.070715,0.214239,13816.0,2.424323,7.344717,11239.0,1.972132,5.974759,26091.0,4.578244,543800.0,95.421756,198741.0,34.873511,371150.0,65.126489,237405.0,138106.0,94784.0,39.925023,43322.0,18.248141,9283.0,34039.0,99299.0,79249.0,33.381353,20050.0,8.445483,2.30,252977.0,237405.0,93.844500,15572.0,6.155500,237405.0,131340.0,55.323182,106065.0,44.676818
2,"Dickson County, Tennessee",0500000US47043,43156.0,1538.0,1437.0,3412.0,3185.0,2701.0,2706.0,1686.0,1584.0,1726.0,1601.0,957.0,957.0,1744.0,1749.0,3010.0,3108.0,3535.0,3581.0,2828.0,2944.0,2036.0,2066.0,1304.0,1520.0,656.0,1041.0,138.0,410.0,2975.0,6.893595,3270.0,7.577162,3327.0,7.709241,1914.0,4.435073,3493.0,8.093892,6118.0,14.176476,7116.0,16.489017,6479.0,15.012976,4102.0,9.505051,2824.0,6.543702,1697.0,3.932246,548.0,1.269812,8511.0,19.721476,11486.0,26.615071,22499.0,52.134118,9171.0,21.250811,5069.0,11.745760,40243.0,93.250070,2913.0,1978.0,4.583372,67.902506,172.0,0.398554,5.904566,116.0,0.268792,3.982149,5.0,0.011586,0.171644,204.0,0.472704,7.003090,438.0,1.014923,15.036045,484.0,1.121513,42672.0,98.878487,3136.0,7.266660,40020.0,92.733340,16473.0,12175.0,9604.0,58.301463,2571.0,15.607357,670.0,1901.0,4298.0,3678.0,22.327445,620.0,3.763735,2.59,17614.0,16473.0,93.522198,1141.0,6.477802,16473.0,12539.0,76.118497,3934.0,23.881503

In [7]:
suffix.to_csv('../../data/Suffix2000SF1.csv', index = False)
tidy.to_csv('../../data/Tidy2000SF1.csv', index = False)