###### Imports and Settings

In [1]:
import pandas as pd
import numpy as np
import requests
#import io
import pickle
from collections import deque
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
pd.set_option('display.width', 150)
from warnings import simplefilter
simplefilter(action="ignore", category=pd.errors.PerformanceWarning)

In [2]:
def percent(x, y):
    return (x/y)*100

## Calculations

# ALL:

In [3]:
data = pd.read_csv('../../Data/SF12010.csv')
coldropper = data.set_index(['NAME', 'GEO_ID'])

In [4]:
data['Population'] = data['agebysex_total_series']
#small groups m and f
data['Male Under 5'] = data['age_m_u5']
data['Female Under 5'] = data['age_f_u5']
data['Male 5 to 9'] = data['age_m_5to9']
data['Female 5 to 9'] = data['age_f_5to9']
data['Male 5 to 14'] = data['age_m_5to9'] + data['age_m_10to14']
data['Female 5 to 14'] = data['age_f_5to9'] + data['age_f_10to14']
data['Male 15 to 24'] = data['age_m_15to17'] + data['age_m_18to19']+data['age_m_20']+data['age_m_21']+data['age_m_22to24']
data['Female 15 to 24'] = data['age_f_15to17'] + data['age_f_18to19']+data['age_f_20']+data['age_f_21']+data['age_f_22to24']
data['Male 10 to 14'] = data['age_m_10to14']
data['Female 10 to 14'] = data['age_f_10to14']
data['Male 15 to 17'] = data['age_m_15to17']
data['Female 15 to 17'] = data['age_f_15to17']
data['Male 18 to 24'] = data['age_m_18to19']+data['age_m_20']+data['age_m_21']+data['age_m_22to24']
data['Female 18 to 24'] = data['age_f_18to19']+data['age_f_20']+data['age_f_21']+data['age_f_22to24']
data['Male 25 to 34'] = data['age_m_25to29']+data['age_m_30to34']
data['Female 25 to 34'] = data['age_f_25to29']+data['age_f_30to34']
data['Male 35 to 44'] = data['age_m_35to39']+data['age_m_40to44']
data['Female 35 to 44'] = data['age_f_35to39']+data['age_f_40to44']
data['Male 45 to 54'] = data['age_m_45to49']+data['age_m_50to54']
data['Female 45 to 54'] = data['age_f_45to49']+data['age_f_50to54']
data['Male 55 to 64'] = data['age_m_55to59']+data['age_m_60to61']+data['age_m_62to64']
data['Female 55 to 64'] = data['age_f_55to59']+data['age_f_60to61']+data['age_f_62to64']
data['Male 65 to 74'] = data['age_m_65to66']+data['age_m_67to69']+data['age_m_70to74']
data['Female 65 to 74'] = data['age_f_65to66']+data['age_f_67to69']+data['age_f_70to74']
data['Male 75 to 84'] = data['age_m_75to79']+data['age_m_80to84']
data['Female 75 to 84'] = data['age_f_75to79']+data['age_f_80to84']
data['Male 85 and Older'] = data['age_m_85+']
data['Female 85 and Older'] = data['age_f_85+']
#age group breakouts
data['Age:Under 5'] = data['Male Under 5']+data['Female Under 5']
data['Age %:Under 5'] = percent(data['Age:Under 5'], data['Population'])
data['Age:5 to 9'] = data['Male 5 to 9']+data['Female 5 to 9']
data['Age%:5 to 9'] = percent(data['Age:5 to 9'], data['Population'])
data['Age:10 to 14'] = data['Male 10 to 14']+data['Female 10 to 14']
data['Age%:10 to 14'] = percent(data['Age:10 to 14'], data['Population'])
data['Age:15 to 17'] = data['Male 15 to 17']+data['Female 15 to 17']
data['Age%:15 to 17'] = percent(data['Age:15 to 17'], data['Population'])
data['Age:18 to 24'] = data['Male 18 to 24']+data['Female 18 to 24']
data['Age%:18 to 24'] = percent(data['Age:18 to 24'], data['Population'])
data['Age:25 to 34'] = data['Male 25 to 34']+data['Female 25 to 34']
data['Age%:25 to 34'] = percent(data['Age:25 to 34'], data['Population'])
data['Age:35 to 44'] = data['Male 35 to 44']+data['Female 35 to 44']
data['Age%:35 to 44'] = percent(data['Age:35 to 44'], data['Population'])
data['Age:45 to 54'] = data['Male 35 to 44']+data['Female 45 to 54']
data['Age%:45 to 54'] = percent(data['Age:45 to 54'], data['Population'])
data['Age:55 to 64'] = data['Male 55 to 64']+data['Female 55 to 64']
data['Age%:55 to 64'] = percent(data['Age:55 to 64'], data['Population'])
data['Age:65 to 74'] = data['Male 65 to 74']+data['Female 65 to 74']
data['Age%:65 to 74'] = percent(data['Age:65 to 74'], data['Population'])
data['Age:75 to 84'] = data['Male 75 to 84']+data['Female 75 to 84']
data['Age%:75 to 84'] = percent(data['Age:75 to 84'], data['Population'])
data['Age:85 and Older'] = data['Male 85 and Older']+data['Female 85 and Older']
data['Age%:85 and Older'] = percent(data['Age:85 and Older'], data['Population'])
data['Age:School Age 5 to 18'] = data['Age:5 to 9']+data['Age:10 to 14']+data['Age:15 to 17']
data['Age%:School Age 5 to 18'] = percent(data['Age:School Age 5 to 18'], data['Population'])
#age brackets
u18list = [data['Male Under 5'],data['Female Under 5'],data['Male 5 to 9'],data['Female 5 to 9'],data['Male 10 to 14'],data['Female 10 to 14'],data['Male 15 to 17'],
           data['Female 15 to 17']]
data['Age:Under 18'] = sum(u18list)
data['Age%:Under 18'] = percent(data['Age:Under 18'], data['Population'])
eighteento54list = [data['Male 18 to 24'],data['Female 18 to 24'],data['Male 25 to 34'],data['Female 25 to 34'],data['Male 35 to 44'],data['Female 35 to 44'],
              data['Male 45 to 54'],data['Female 45 to 54']]
data['Age:18 to 54'] = sum(eighteento54list)
data['Age%:18 to 54'] = percent(data['Age:18 to 54'], data['Population'])
fifty5pluslist = [data['Male 55 to 64'],data['Female 55 to 64'],data['Male 65 to 74'],data['Female 65 to 74'],data['Male 75 to 84'],data['Female 75 to 84'],
                  data['Male 85 and Older'],data['Female 85 and Older']]
data['Age:55 and Older'] = sum(fifty5pluslist)
data['Age%:55 and Older'] = percent(data['Age:55 and Older'], data['Population'])
#65+
sixty5pluslist = [data['Male 65 to 74'],data['Female 65 to 74'],data['Male 75 to 84'],data['Female 75 to 84'],data['Male 85 and Older'],data['Female 85 and Older']]
data['Age:65 and Older'] = sum(sixty5pluslist)
data['Age%:65 and Older'] = percent(data['Age:65 and Older'], data['Population'])
#race and ethnicity
#White Alone
data['White Alone'] = data['raceeth_white_alone']
data['White Alone %'] = percent(data['White Alone'],data['Population'])
#Population not White
data['Non-White Population: Race'] = data['Population'] - data['White Alone']
#Black or African American Alone 
data['Black or African American Alone'] = data['raceeth_blackafricanamerican_alone']
data['Black or African American Alone %'] = percent(data['Black or African American Alone'],data['Population'])
data['Black or African American Alone % Non-White Population'] = percent(data['Black or African American Alone'], data['Non-White Population: Race'])
#American Indian and Alaska Native Alone
data['American Indian Alaska Native Alone'] = data['raceeth_americanindianalaskanative_alone']
data['American Indian Alaska Native Alone %'] = percent(data['American Indian Alaska Native Alone'], data['Population'])
data['American Indian Alaska Native Alone % Non-White Population'] = percent(data['American Indian Alaska Native Alone'], data['Non-White Population: Race'])
#Asian Alone
data['Asian Alone'] = data['raceeth_asian_alone']
data['Asian Alone %'] = percent(data['Asian Alone'], data['Population'])
data['Asian Alone % Non-White Population'] = percent(data['Asian Alone'], data['Non-White Population: Race'])
#Native Hawaiian Other Pacific Islander Alone
data['Native Hawaiian Other Pacific Islander Alone'] = data['raceeth_nativehawaiianotherpacificislander_alone']
data['Native Hawaiian Other Pacific Islander Alone %'] = percent(data['Native Hawaiian Other Pacific Islander Alone'], data['Population'])
data['Native Hawaiian Other Pacific Islander Alone % Non-White Population'] = percent(data['Native Hawaiian Other Pacific Islander Alone'], data['Non-White Population: Race'])
#Some Other Race Alone
data['Some Other Race Alone'] = data['raceeth_someotherrace_alone']
data['Some Other Race Alone %'] = percent(data['Some Other Race Alone'], data['Population'])
data['Some Other Race Alone % Non-White Population'] = percent(data['Some Other Race Alone'], data['Non-White Population: Race'])
#Two or More Races
data['Two or More Races'] = data['raceeth_twoormoreraces_alone']
data['Two or More Races %'] = percent(data['Two or More Races'], data['Population'])
data['Two or More Races % Non-White Population'] = percent(data['Two or More Races'], data['Non-White Population: Race'])
#Hispanic or Latino
data['Hispanic or Latino'] = data['raceeth_hispanicorlatino']
data['Hispanic or Latino %'] = percent(data['Hispanic or Latino'], data['Population'])
#not hispanic or latino
data['Not Hispanic or Latino'] = data['Population'] - data['Hispanic or Latino']
data['Not Hispanic or Latino %'] = percent(data['Not Hispanic or Latino'], data['Population'])
#Data Minority
data['Minority'] = data['Population'] - data['raceeth_whitealone_nothispanicorlatino']
data['Minority %'] = percent(data['Minority'], data['Population'])
#not minority
data['White Alone Not Hispanic or Latino'] = data['raceeth_whitealone_nothispanicorlatino']
data['White Alone Not Hispanic or Latino %'] = data['White Alone Not Hispanic or Latino']/data['Population']
#household type
data['Total Households'] = data['hhtype_total_series']
data['Family Households'] = data['hhtype_familyhh']
data['Family Households: Married Couple Family'] = data['hhtype_familyhh_marriedcouplefam']
data['Household Type%: Family, Married Couple Households'] = percent(data['Family Households: Married Couple Family'], data['hhtype_total_series'])
data['Family Households: Not Married Couple Family'] = data['hhtype_familyhh_otherfam']
data['Household Type%: Family, Not Married Couple Households'] = percent(data['Family Households: Not Married Couple Family'], data['hhtype_total_series'])
data['Family Households: Not Married Couple: Male no Spouse'] = data['hhtype_familyhh_malenospouse']
data['Family Households: Not Married Couple: Female no Spouse'] = data['hhtype_familyhh_femalenospouse']
data['Nonfamily Households'] = data['hhtype_nonfamhh']
data['Nonfamily Households: Householder Alone'] = data['hhtype_nonfamhh_householderalone']
data['Household Type%: Nonfamily, Householder Alone'] = percent(data['Nonfamily Households: Householder Alone'], data['hhtype_total_series'])
data['Nonfamily Households: Householder not Alone'] = data['hhtype_nonfamhh_householdernotalone']
data['Household Type%: Nonfamily, Householder Not Alone'] = percent(data['Nonfamily Households: Householder not Alone'], data['hhtype_total_series'])
#avg hh size
data['Average Household Size'] = data['hhsize_avg']
#occupancy
data['Occupancy:Total Households'] = data['occupancy_total_series']
data['Occupancy:Occupied Units'] = data['occupancy_occupiedunits']
data['Occupancy%:Occupied Units'] = percent(data['Occupancy:Occupied Units'], data['Occupancy:Total Households'])
data['Occupancy:Vacant Units'] = data['occupancy_vacantunits']
data['Occupancy%:Vacant Units'] = percent(data['Occupancy:Vacant Units'], data['Occupancy:Total Households'])
#tenure
data['Tenure:Total Households'] = data['tenure_total_series']
data['Tenure:Owners'] = data['tenure_owneroccunits_mortgage']+data['tenure_owneroccunits_nomortgage']
data['Tenure%:Owners'] = percent(data['Tenure:Owners'], data['Tenure:Total Households'])
data['Tenure:Renters'] = data['tenure_renteroccunits']
data['Tenure%:Renters'] = percent(data['Tenure:Renters'], data['Tenure:Total Households'])

In [5]:
cols = coldropper.columns
data = data.drop(columns = cols)
data.head(3)

,NAME,GEO_ID,Population,Male Under 5,Female Under 5,Male 5 to 9,Female 5 to 9,Male 5 to 14,Female 5 to 14,Male 15 to 24,Female 15 to 24,Male 10 to 14,Female 10 to 14,Male 15 to 17,Female 15 to 17,Male 18 to 24,Female 18 to 24,Male 25 to 34,Female 25 to 34,Male 35 to 44,Female 35 to 44,Male 45 to 54,Female 45 to 54,Male 55 to 64,Female 55 to 64,Male 65 to 74,Female 65 to 74,Male 75 to 84,Female 75 to 84,Male 85 and Older,Female 85 and Older,Age:Under 5,Age %:Under 5,Age:5 to 9,Age%:5 to 9,Age:10 to 14,Age%:10 to 14,Age:15 to 17,Age%:15 to 17,Age:18 to 24,Age%:18 to 24,Age:25 to 34,Age%:25 to 34,Age:35 to 44,Age%:35 to 44,Age:45 to 54,Age%:45 to 54,Age:55 to 64,Age%:55 to 64,Age:65 to 74,Age%:65 to 74,Age:75 to 84,Age%:75 to 84,Age:85 and Older,Age%:85 and Older,Age:School Age 5 to 18,Age%:School Age 5 to 18,Age:Under 18,Age%:Under 18,Age:18 to 54,Age%:18 to 54,Age:55 and Older,Age%:55 and Older,Age:65 and Older,Age%:65 and Older,White Alone,White Alone %,Non-White Population: Race,Black or African American Alone,Black or African American Alone %,Black or African American Alone % Non-White Population,American Indian Alaska Native Alone,American Indian Alaska Native Alone %,American Indian Alaska Native Alone % Non-White Population,Asian Alone,Asian Alone %,Asian Alone % Non-White Population,Native Hawaiian Other Pacific Islander Alone,Native Hawaiian Other Pacific Islander Alone %,Native Hawaiian Other Pacific Islander Alone % Non-White Population,Some Other Race Alone,Some Other Race Alone %,Some Other Race Alone % Non-White Population,Two or More Races,Two or More Races %,Two or More Races % Non-White Population,Hispanic or Latino,Hispanic or Latino %,Not Hispanic or Latino,Not Hispanic or Latino %,Minority,Minority %,White Alone Not Hispanic or Latino,White Alone Not Hispanic or Latino %,Total Households,Family Households,Family Households: Married Couple Family,"Household Type%: Family, Married Couple Households",Family Households: Not Married Couple Family,"Household Type%: Family, Not Married Couple Households",Family Households: Not Married Couple: Male no Spouse,Family Households: Not Married Couple: Female no Spouse,Nonfamily Households,Nonfamily Households: Householder Alone,"Household Type%: Nonfamily, Householder Alone",Nonfamily Households: Householder not Alone,"Household Type%: Nonfamily, Householder Not Alone",Average Household Size,Occupancy:Total Households,Occupancy:Occupied Units,Occupancy%:Occupied Units,Occupancy:Vacant Units,Occupancy%:Vacant Units,Tenure:Total Households,Tenure:Owners,Tenure%:Owners,Tenure:Renters,Tenure%:Renters
0,"Williamson County, Tennessee",0500000US47187,183182.0,6324.0,6039.0,7997.0,7718.0,16369.0,15588.0,10270.0,9625.0,8372.0,7870.0,4712.0,4597.0,5558.0,5028.0,8437.0,9735.0,14063.0,15361.0,15079.0,16388.0,10934.0,11163.0,5028.0,5457.0,2190.0,3045.0,642.0,1445.0,12363.0,6.749026,15715.0,8.578900,16242.0,8.866592,9309.0,5.081831,10586.0,5.778952,18172.0,9.920189,29424.0,16.062714,30451.0,16.623358,22097.0,12.062866,10485.0,5.723816,5235.0,2.857814,2087.0,1.139304,41266.0,22.527323,53629.0,29.276348,89649.0,48.939852,39904.0,21.783800,17807.0,9.720933,163728.0,89.379961,19454.0,7941.0,4.335033,40.819369,396.0,0.216178,2.035571,5517.0,3.011759,28.359206,82.0,0.044764,0.421507,2784.0,1.519800,14.310682,2734.0,1.492505,14.053665,8166.0,4.457862,175016.0,95.542138,24413.0,13.327183,158769.0,0.866728,64886.0,51242.0,44172.0,68.076318,7070.0,10.896033,1734.0,5336.0,13644.0,11505.0,17.731098,2139.0,3.296551,2.81,68498.0,64886.0,94.726853,3612.0,5.273147,64886.0,52717.0,81.245569,12169.0,18.754431
1,"Wilson County, Tennessee",0500000US47189,113993.0,3746.0,3572.0,4118.0,3933.0,8389.0,8019.0,6761.0,6371.0,4271.0,4086.0,2473.0,2362.0,4288.0,4009.0,6254.0,6853.0,8370.0,8784.0,9036.0,9536.0,7037.0,7397.0,4199.0,4419.0,1627.0,2278.0,415.0,930.0,7318.0,6.419692,8051.0,7.062714,8357.0,7.331152,4835.0,4.241489,8297.0,7.278517,13107.0,11.498074,17154.0,15.048292,17906.0,15.707982,14434.0,12.662181,8618.0,7.560113,3905.0,3.425649,1345.0,1.179897,21243.0,18.635355,28561.0,25.055047,57130.0,50.117112,28302.0,24.827840,13868.0,12.165659,101379.0,88.934408,12614.0,7297.0,6.401270,57.848422,395.0,0.346513,3.131441,1276.0,1.119367,10.115744,44.0,0.038599,0.348819,1751.0,1.536059,13.881402,1851.0,1.623784,14.674172,3691.0,3.237918,110302.0,96.762082,14276.0,12.523576,99717.0,0.874764,42563.0,32177.0,25571.0,60.078002,6606.0,15.520523,1845.0,4761.0,10386.0,8452.0,19.857623,1934.0,4.543853,2.65,45568.0,42563.0,93.405460,3005.0,6.594540,42563.0,33730.0,79.247234,8833.0,20.752766
2,"Houston County, Tennessee",0500000US47083,8426.0,245.0,228.0,304.0,276.0,591.0,574.0,516.0,483.0,287.0,298.0,186.0,168.0,330.0,315.0,442.0,425.0,506.0,544.0,599.0,588.0,568.0,614.0,430.0,440.0,203.0,269.0,44.0,117.0,473.0,5.613577,580.0,6.883456,585.0,6.942796,354.0,4.201282,645.0,7.654878,867.0,10.289580,1050.0,12.461429,1094.0,12.983622,1182.0,14.028009,870.0,10.325184,472.0,5.601709,161.0,1.910752,1519.0,18.027534,1992.0,23.641111,3749.0,44.493235,2685.0,31.865654,1503.0,17.837645,8015.0,95.122241,411.0,193.0,2.290529,46.958637,24.0,0.284833,5.839416,25.0,0.296701,6.082725,3.0,0.035604,0.729927,35.0,0.415381,8.515815,131.0,1.554712,31.873479,129.0,1.530976,8297.0,98.469024,495.0,5.874674,7931.0,0.941253,3349.0,2285.0,1752.0,52.314124,533.0,15.915199,165.0,368.0,1064.0,942.0,28.127799,122.0,3.642878,2.46,4188.0,3349.0,79.966571,839.0,20.033429,3349.0,2544.0,75.962974,805.0,24.037026

In [7]:
data.to_csv('../../Outputs/2010SF1.csv', index = False)