###### Imports and Settings

In [2]:
import pandas as pd
import numpy as np
import requests
from functools import reduce
import matplotlib.pyplot as plt
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
pd.set_option('display.width', 150)

# This notebook outlines the download and formatting process for the Center for Neighborhood Technology's Housing and Transportation Cost Index as well as the data combined from our end for counties and places in the GNRC operating region.  

Go to this page: https://htaindex.cnt.org/download/  
Upon registering for access, download the following documents:  
+ HTA Index for Counties in Tennessee and Kentucky  
+ HTA Index for MPOs  
+ HTA Index for Block Groups in Tennessee  

Save these csvs as they come in the Data Downloads folder of Parent Data Gathering  

### We

In [3]:
kycos = pd.read_csv('../../Data Downloads/htaindex2019_data_counties_21.csv')
tncos = pd.read_csv('../../Data Downloads/htaindex2019_data_counties_47.csv')
mpos = pd.read_csv('../../Data Downloads/htaindex2019_data_mpos_.csv')
tnbg = pd.read_csv('../../Data Downloads/htaindex2019_data_blkgrps_47.csv')

In [4]:
tncos.head()

,county,name,cbsa,blkgrps,population,households,land_acres,ht_ami,ht_80ami,ht_nmi,h_ami,h_80ami,h_nmi,t_ami,t_80ami,t_nmi,co2_per_hh_local,co2_per_acre_local,autos_per_hh_ami,autos_per_hh_80ami,autos_per_hh_nmi,vmt_per_hh_ami,vmt_per_hh_80ami,vmt_per_hh_nmi,pct_transit_commuters_ami,pct_transit_commuters_80ami,pct_transit_commuters_nmi,t_cost_ami,t_cost_80ami,t_cost_nmi,auto_ownership_cost_ami,auto_ownership_cost_80ami,auto_ownership_cost_nmi,vmt_cost_ami,vmt_cost_80ami,vmt_cost_nmi,transit_cost_ami,transit_cost_80ami,transit_cost_nmi,transit_trips_ami,transit_trips_80ami,transit_trips_nmi,compact_ndx,emp_ovrll_ndx,res_density,gross_hh_density,hh_gravity,frac_sfd,emp_gravity,emp_ndx,block_size,intersection_density,avg_block_perimeter_meters,h_cost,median_smoc,median_gross_rent,pct_owner_occupied_hu,pct_renter_occupied_hu
0,"""47001""","""Anderson""","""Knoxville, TN""",53.0,76061.0,30541.0,215809.79,49,59,43,23,28,20,26,31,24,7.96,4.26,1.89,2,2,20355,19802,21142,0,0,1,14396,13349,14902,11324,10359,11711,3062,2980,3180,10,10,10,12,13,13,2.5,2.5,0.49,0.14,5324,69,6960,84,57,21,2704,1034,1148,692,72,28
1,"""47003""","""Bedford""","""Shelbyville, TN""",25.0,48292.0,17029.0,303126.80,56,67,45,24,30,19,32,37,26,9.96,2.74,2.06,2,2,24108,23276,24285,0,0,0,15978,14815,16255,12344,11305,12595,3627,3503,3653,8,8,7,9,9,9,1.1,1.4,0.27,0.06,3366,71,3901,86,111,9,3247,1015,1093,735,72,28
2,"""47005""","""Benton""","""""",13.0,16140.0,6762.0,252355.58,65,79,42,28,35,17,37,44,26,9.12,0.81,1.87,2,2,21844,21085,24099,0,0,0,13918,13305,16165,10625,10126,12533,3287,3173,3625,6,6,7,7,7,8,1.3,1.0,0.15,0.03,1815,67,1744,86,143,7,3828,871,943,630,82,18
3,"""47007""","""Bledsoe""","""""",8.0,14836.0,4894.0,260113.80,61,75,45,26,33,19,35,42,26,10.57,0.33,2.03,2,2,25344,24462,25852,0,0,0,15319,14685,16622,11498,10998,12727,3814,3681,3889,7,7,7,9,8,8,1.2,0.9,0.12,0.02,2124,65,1796,86,239,6,3955,974,1151,498,78,22
4,"""47009""","""Blount""","""Knoxville, TN""",78.0,129927.0,50557.0,357644.04,53,63,47,25,32,22,27,32,25,8.83,4.56,1.96,2,2,21337,20801,22103,1,1,1,14936,13890,15430,11715,10748,12093,3210,3130,3325,11,11,12,14,14,15,2.0,2.9,0.43,0.14,6091,74,7745,84,60,20,3939,1153,1265,686,78,22